import type { Metadata } from "next";
import localFont from "next/font/local";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const humaneFont = localFont({
  src: "./fonts/Humane-Bold.woff2",
  variable: "--font-humane",
});

const enigmaFont = localFont({
  src: "./fonts/enigma.otf",
  variable: "--font-enigma",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${humaneFont.variable} ${enigmaFont.variable} ${openSans.variable} antialiased`}>
      <body>
        {children}
      </body>
    </html>
  );
}
